using System;
using Dime.Scheduler.Sdk.Import;
using Xunit;

namespace Dime.Scheduler.Sdk.Tests.Import
{
    public class TaskTests
    {
        [Fact]
        public void Task_ToImportRequest_Append_AllShouldMapParameters()
        {
            Task model = new()
            {
                SourceApp = "APP",
                SourceType = "TYPE",
                JobNo = "JOB1",
                TaskNo = "TASK 1",
                SentFromBackOffice = true,
                Name = "Name",
                Category = "Cat",
                Importance = 5,
                StartDate = "1",
                Type = "1",
                Description = "Desc",
                TimeMarker = "TM",
                Subject = "Sub",
                Body = "Body",
                EndDate = "END",
                CalendarCode = "CODE",
                ActualEndDate = new DateTime(2020, 1, 1),
                ActualResponseDateTime = new DateTime(2020, 1, 1),
                ActualStartDate = new DateTime(2020, 1, 1),
                AppointmentEarliestAllowedtime = new DateTime(2020, 1, 1),
                AppointmentLatestAllowedtime = new DateTime(2020, 1, 1),
                AppointmentTemplate = "TP",
                BaseLineEndDatetime = "1",
                BaseLinePercentDone = "25",
                BaseLineStartDatetime = "D",
                BulkPlanningQty = "QTY",
                CertificateNo = "CERT",
                CheckAppointments = true,
                ConfirmedEndDate = new DateTime(2020, 1, 1),
                ConfirmedStartDate = new DateTime(2020, 1, 1),
                ConstraintDatetime = "1",
                ConstraintType = "A",
                ContainerIndex = "1",
                ContainerName = "NAME",
                ContractDescription = "DESC",
                ContractEndDate = new DateTime(2020, 1, 1),
                ContractNo = "NO",
                ContractStartDate = new DateTime(2020, 1, 1),
                ContractType = "TYPE",
                DeadLinetime = "TIME",
                DoNotCountAppointmentResource = true,
                Duration = "DURATION",
                DurationInSeconds = "DURATION",
                ExpectedResponseDateTime = new DateTime(2020, 1, 1),
                FreeBit1 = true,
                FreeBit2 = true,
                FreeBit3 = true,
                FreeBit4 = true,
                FreeBit5 = true,
                FreeDate1 = new DateTime(2020, 1, 1),
                FreeDate2 = new DateTime(2020, 1, 1),
                FreeDate3 = new DateTime(2020, 1, 1),
                FreeDate4 = new DateTime(2020, 1, 1),
                FreeDate5 = new DateTime(2020, 1, 1),
                FreeDecimal1 = 1,
                FreeDecimal2 = 2,
                FreeDecimal3 = 3,
                FreeDecimal4 = 4,
                FreeDecimal5 = 5,
                FreeText1 = "Text",
                FreeText10 = "Text",
                FreeText11 = "Text",
                FreeText12 = "Text",
                FreeText13 = "Text",
                FreeText14 = "Text",
                FreeText15 = "Text",
                FreeText16 = "Text",
                FreeText17 = "Text",
                FreeText18 = "Text",
                FreeText19 = "Text",
                FreeText2 = "Text",
                FreeText20 = "Text",
                FreeText3 = "Text",
                FreeText4 = "Text",
                FreeText5 = "Text",
                FreeText6 = "Text",
                FreeText7 = "Text",
                FreeText8 = "Text",
                FreeText9 = "Text",
                IRISArea = "AREA",
                IRISFault = "FAULT",
                IRISReason = "REASON",
                IRISResolution = "RESOLUTION",
                IRISSymptom = "SYMPTON",
                IgnoreCalendars = "true",
                Index = "1",
                InfiniteTask = true,
                IsComplete = true,
                LaborWarrantyEndDate = new DateTime(2020, 1, 1),
                LaborWarrantyStartDate = new DateTime(2020, 1, 1),
                LocationDescription = "DESC",
                ManuallyScheduled = "True",
                Note = "NOTE",
                OverRuleGanttPlanning = "TRUE",
                ParentTaskNo = "TPARENT",
                PartsWarrantyEndDate = new DateTime(2020, 1, 1),
                PartsWarrantyStartDate = new DateTime(2020, 1, 1),
                PercentDone = "25",
                Pin = "PIN",
                PlanningQty = "QTY",
                PlanningUOM = "UOM",
                PlanningUOMConversion = "CONVERSION",
                PredecessorLag = "LAG",
                PredecessorTaskNo = "TASK",
                RequestedEndDate = new DateTime(2020, 1, 1),
                RequestedEndTime = new TimeSpan(1,1,1,0),
                RequestedStartDate = new DateTime(2020, 1, 1),
                RequestedStartTime = new TimeSpan(1,1,1,0),
                RequiredNoResources = "0",
                RequiredTotalDuration = "1",
                RequiredTotalDurationInSeconds = 100,
                RoundToUOM = "UOM",
                SchedulingMode = "MODE",
                ServiceClass = "CLASS",
                ServiceGroup = "GROUP",
                ServiceName = "NAME",
                ServiceNo = "NO",
                ServiceSerialNo = "SERIAL",
                ShortDescription = "DESc",
                Skill1 = "SKILL",
                Skill2 = "SKILL",
                Skill3 = "SKILL",
                Status = "STATUS",
                TaskOpenAsOftime = new DateTime(2020, 1, 1),
                TaskOpenTilltime = new DateTime(2020, 1, 1),
                TaskType = 1,
                Url1 = "URL",
                Url2 = "URL",
                Url3 = "URL",
                UrlDescription1 = "URL DESC",
                UrlDescription2 = "URL DESC",
                UrlDescription3 = "URL DESC",
                UseFixPlanningQty = true
            };
            ImportRequest importRequest = model.ToImportRequest(TransactionType.Append);
            importRequest.AssertEqualParameterCollectionCount();
        }
    }
}